[package]
name = "graphics_test"
version = "0.1.0"
authors = ["heropoo <aiyouyou1000@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#glfw="0.30.0"
kiss3d = "0.20.1"
