[package]
name = "actix_web_demo"
version = "0.1.0"
authors = ["heropoo <aiyouyou1000@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
#serde = "1.0.126"
#serde_json = "1.0"